version: "3"
services:
  node:
    image: "node:10-alpine"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: "npm start"
